INSERT INTO users (username, password, status, balance) VALUES ('user1', 'password1', 'active', 1.00);
INSERT INTO users (username, password, status, balance) VALUES ('user2', 'password2', 'active', 2.00);
INSERT INTO users (username, password, status, balance) VALUES ('user3', 'password3', 'active', 3.00);
INSERT INTO users (username, password, status, balance) VALUES ('user4', 'password4', 'active', 100.00);
INSERT INTO users (username, password, status, balance) VALUES ('user5', 'password5', 'active', 100.00);
INSERT INTO users (username, password, status, balance) VALUES ('user6', 'password6', 'active', 100.00);
INSERT INTO users (username, password, status, balance) VALUES ('user7', 'password7', 'active', 100.00);
INSERT INTO users (username, password, status, balance) VALUES ('user8', 'password8', 'active', 100.00);
INSERT INTO users (username, password, status, balance) VALUES ('user9', 'password9', 'active', 100.00);
INSERT INTO operations (type, cost) VALUES ('ADDITION', 0.10);
INSERT INTO operations (type, cost) VALUES ('SUBTRACTION', 0.10);
INSERT INTO operations (type, cost) VALUES ('MULTIPLICATION', 0.20);
INSERT INTO operations (type, cost) VALUES ('DIVISION', 0.20);
INSERT INTO operations (type, cost) VALUES ('SQUARE_ROOT', 0.30);
INSERT INTO operations (type, cost) VALUES ('RANDOM_STRING', 0.10);